Annotate.set_defaults(
  'routes'                  => 'false',
  'position_in_routes'      => 'after',
  'position_in_class'       => 'after',
  'position_in_test'        => 'after',
  'position_in_fixture'     => 'after',
  'position_in_factory'     => 'after',
  'position_in_serializer'  => 'after',
  'show_foreign_keys'       => 'true',
  'show_indexes'            => 'true',
  'exclude_tests'           => 'false',
  'exclude_fixtures'        => 'false',
  'exclude_factories'       => 'false',
  'exclude_serializers'     => 'false',
  'exclude_scaffolds'       => 'false',
  'exclude_controllers'     => 'false',
  'exclude_helpers'         => 'false',
  'ignore_model_sub_dir'    => 'false',
  'ignore_unknown_models'   => 'false',
  'skip_on_db_migrate'      => 'false',
  'format_bare'             => 'true',
  'sort'                    => 'false',
  'force'                   => 'false',
  'trace'                   => 'false',
)
