---
:concurrency: 2
staging:
  :concurrency: 3
production:
  :concurrency: 5
:queues:
  - push-notification
  - order-canceletion
  - driver-finder
  - notification
  - devise-mailer
  - apn-token-cleaner
  - default
